- CHANGELOG.md
- deploy/operator.yaml
- docs/tutorials/secured_nifi_cluster_on_gcp/terraform/env/demo.tfvars
- helm/nifikop/Chart.yaml
- helm/nifikop/README.md
- helm/nifikop/values.yaml
- version/version.go
- website/blog/2020-06-30-secured_nifi_cluster_on_gcp_with_external_dns.md
- website/docs/2_setup/3_install/1_customizable_install_with_helm.md
- website/docs/6_contributing/1_developer_guide.md
This PR contains the bump of operator and chart Helm to version 0.2.0
Release new stable features
> [Version/Operator] Bump version to 0.2.0

- docs/tutorials/secured_nifi_cluster_on_gcp/kubernetes/nifikop/nifi.orange.com_nificlusters_crd.yaml
- docs/tutorials/secured_nifi_cluster_on_gcp/kubernetes/nifikop/nifi.orange.com_nifiusers_crd.yaml
- docs/tutorials/secured_nifi_cluster_on_gcp/terraform/env/demo.tfvars
- docs/tutorials/secured_nifi_cluster_on_gcp/terraform/nifi.tf
- docs/tutorials/secured_nifi_cluster_on_gcp_with_external_dns/kubernetes/nifi/secured_nifi_cluster.yaml
- website/blog/2020-05-20-secured_nifi_cluster_on_gcp.md
- website/blog/2020-06-30-secured_nifi_cluster_on_gcp_with_external_dns.md
| Related tickets |-
Update blog post.
To make it works with last release changes.
> Fix tutorial version

- CHANGELOG.md
- Makefile
- config/samples/simplenificluster.yaml
- config/samples/tls_secured_nificluster.yaml
- docs/tutorials/secured_nifi_cluster_on_gcp/kubernetes/nifi/secured_nifi_cluster.yaml
- docs/tutorials/secured_nifi_cluster_on_gcp_with_external_dns/kubernetes/nifi/secured_nifi_cluster.yaml
- website/docs/3_tasks/2_security/2_authentication/1_oidc.md
- website/docs/6_contributing/1_developer_guide.md
| Related tickets | #23 
This PR fix some documentations
> [Fix/Documentation] Pattern & versions

- CHANGELOG.md
- pkg/pki/certmanagerpki/certmanager.go
- pkg/pki/certmanagerpki/certmanager_pki.go
| API breaks?     | no|
| Related tickets | fixes #27 
This PR fix the namespace for ca cert resources.
Without it the cluster resource never finalize
> [Fix/Operator] PKI Finalizer namespace

- CHANGELOG.md
- deploy/operator.yaml
- helm/nifikop/Chart.yaml
- helm/nifikop/README.md
- helm/nifikop/values.yaml
- version/version.go
- website/blog/2020-06-30-secured_nifi_cluster_on_gcp_with_external_dns.md
- website/docs/2_setup/3_install/1_customizable_install_with_helm.md
- website/docs/6_contributing/1_developer_guide.md
This PR contains the bump of operator and chart Helm to version 0.2.1
Release new stable features
> [Version/Operator] Bump version to 0.2.1

- CHANGELOG.md
- README.md
| Related tickets | -
Fix the slack link
> [Fix/Documentation] slack link

- CHANGELOG.md
- deploy/operator.yaml
- helm/nifikop/Chart.yaml
- helm/nifikop/README.md
- helm/nifikop/values.yaml
- version/version.go
- website/docs/2_setup/3_install/1_customizable_install_with_helm.md
- website/docs/6_contributing/1_developer_guide.md
This PR contains the bump of operator and chart Helm to version 0.3.0
> [Version/Operator] Bump version 0.3.0

- CHANGELOG.md
- pkg/resources/nifi/configmap.go
| API breaks?     | no|
| Related tickets |
It contains a fix on `nifi.properties` merge with readOnlyConfig.
We re-order the merge to be sure that the ReadOnlyConfig will be merged.
> [Hotfix/Operator] nifi.properties merge

- CHANGELOG.md
- deploy/operator.yaml
- helm/nifikop/Chart.yaml
- helm/nifikop/README.md
- helm/nifikop/values.yaml
- version/version.go
- website/docs/2_setup/3_install/1_customizable_install_with_helm.md
- website/docs/6_contributing/1_developer_guide.md
This PR contains the bump of operator and chart Helm to version 0.3.1
> [Version/Operator] Bump version 0.3.1

- CHANGELOG.md
- deploy/operator.yaml
- helm/nifikop/Chart.yaml
- helm/nifikop/README.md
- helm/nifikop/values.yaml
- version/version.go
- website/docs/2_setup/3_install/1_customizable_install_with_helm.md
- website/docs/6_contributing/1_developer_guide.md
This PR contains the bump of operator and chart Helm to version 0.4.0-alpha
> [Version/Operator] Bump version 0.4.0-alpha

- CHANGELOG.md
- deploy/operator.yaml
- helm/nifikop/Chart.yaml
- helm/nifikop/README.md
- helm/nifikop/values.yaml
- version/version.go
- website/docs/2_setup/3_install/1_customizable_install_with_helm.md
- website/docs/6_contributing/1_developer_guide.md
This PR contains the bump of operator and chart Helm to version 0.4.0-alpha
> [Version/Operator] Bump version 0.4.1-alpha

- CHANGELOG.md
- deploy/crds/v1/nifi.orange.com_nifiusergroups_crd.yaml
- deploy/crds/v1/nifi.orange.com_nifiusers_crd.yaml
- deploy/crds/v1beta1/nifi.orange.com_nifiusergroups_crd.yaml
- deploy/crds/v1beta1/nifi.orange.com_nifiusers_crd.yaml
- deploy/operator.yaml
- helm/nifikop/Chart.yaml
- helm/nifikop/README.md
- helm/nifikop/crds/nifi.orange.com_nifiusergroups_crd.yaml
- helm/nifikop/crds/nifi.orange.com_nifiusers_crd.yaml
- helm/nifikop/values.yaml
- pkg/apis/nifi/v1alpha1/common_types.go
- version/version.go
- website/docs/2_setup/3_install/1_customizable_install_with_helm.md
- website/docs/6_contributing/1_developer_guide.md
| Related tickets | 
It contains the fix for enum list for some fields.
Without this the resources can't be deployed.
> [Fix/Operator] Access policies enum type list

- CHANGELOG.md
- Makefile
- config/manager/manager.yaml
- helm/nifikop/Chart.yaml
- helm/nifikop/README.md
- helm/nifikop/values.yaml
- version/version.go
- website/docs/2_setup/1_getting_started.md
- website/docs/2_setup/3_install/1_customizable_install_with_helm.md
- website/docs/6_contributing/1_developer_guide.md
This PR contains the bump of operator and chart Helm to version 0.4.3
> [Version/Operator] Bump version 0.4.3

- .circleci/config.yml
| Related tickets |
It contains an upgrade of node version for ci.
> [Hotfix/CI] Upgrade node image version to 14.15.4

- helm/nifikop/templates/deployment.yaml
- site/docs/2_setup/3_install/1_customizable_install_with_helm.md
| New feature?    | yes
| Related tickets | -
Add nodeSelector/affinity/tolerationssupport for Nifikop deployment
Add nodeSelector/affinity/tolerations support for Nifikop deployment
-
> [Feature/Operator] nodeSelector/affinity/tolerations config

- site/docs/3_tasks/2_security/1_ssl.md
- site/website/versioned_docs/version-v0.4.3/3_tasks/2_security/1_ssl.md
- site/website/versioned_docs/version-v0.5.3/3_tasks/2_security/1_ssl.md
- site/website/versioned_docs/version-v0.6.0/3_tasks/2_security/1_ssl.md
- site/website/versioned_docs/version-v0.6.1/3_tasks/2_security/1_ssl.md
| Bug fix?        |yes
| Related tickets | fixes #99
Fix documentation issue about `initialAdminUser`
> fix documentation

- pkg/resources/nifi/nifi.go
| Related tickets | 
This PR contains a change of managing the PVC patch.
It allows to give the ability to update in a good way PVCs configuration.
> [Fix/Operator] Correct the way to update PVC

- .circleci/config.yml
- api/v1alpha1/nifiparametercontext_types.go
- config/crd/bases/nifi.orange.com_nifiparametercontexts.yaml
- helm/nifikop/crds/nifi.orange.com_nifiparametercontexts.yaml
This reverts commit 65671ad436c3ea0f9b93f269583a4e98288e9e3a.
| Bug fix?        | no|yes
| New feature?    | no|yes
| API breaks?     | no|yes
| Deprecations?   | no|yes
| Related tickets | fixes #X, partially #Y, mentioned in #Z
> Revert "Hotfix description (#163)"

- helm/nifikop/templates/deployment.yaml
| New feature?    | yes
| Related tickets | fixes #171
Fix for #171
> #145: fix metrics port in deployment

- config/samples/keycloak-example/README.md
- config/samples/keycloak-example/step-1/kustomization.yaml
- config/samples/keycloak-example/step-1/lets-encrypt-issuer.yaml
- config/samples/keycloak-example/step-1/namespace.yaml
- config/samples/keycloak-example/step-1/nifi-issuer.yaml
- config/samples/keycloak-example/step-1/operator.yaml
- config/samples/keycloak-example/step-1/self-signed-cert.yaml
- config/samples/keycloak-example/step-1/self-signed-issuer.yaml
- config/samples/keycloak-example/step-1/values.yaml
- config/samples/keycloak-example/step-2/cluster.yaml
- config/samples/keycloak-example/step-2/ingress.yaml
- config/samples/keycloak-example/step-2/kustomization.yaml
| Related tickets | none
Customer of mine really wanted Nifi, I've been trying to deploy nifikop for a minute. I decided the best way to give back is to document my setup with some "gotchas" I came across to hopefully help someone else out.
Save semeone else some time?
> [Feature/Documentation]Examples - Keycloak + Nifikop

- CHANGELOG.md
- config/samples/nifi_v1alpha1_nifidataflow.yaml
- pkg/clientwrappers/parametercontext/parametercontext.go
- site/docs/5_references/5_nifi_dataflow.md
| Related tickets | -
A fix to resolve the non-update of the parameter context.
Because the parameter context was not anymore updated.
> Fix parameter context non-update

- api/v1alpha1/nifidataflow_types.go
- pkg/clientwrappers/dataflow/dataflow.go
| Related tickets | -
A fix to replace the 0 position in the flow position by 1.
Because NiFi doesn't accept a 0 as position.
> Fix flow position with 0
